### ISSUE TITLE
NoMatchingPatternError when displaying date64 types in iRuby

### ISSUE THREAD

**Issue by tlrasor** [heronshoes/red_amber#194]
#### Description

I get a `NoMatchingPatternError` when trying to create a dataframe using `date64` types in an iRuby notebook. The dataframe is created just fine, it just can't be displayed due to some issue with the html table creation process.

I am using ruby 3.2.1, red_amber 0.4.0.

#### To Reproduce
Use the following in an iRuby notebook:
```
require 'red_amber' 
include RedAmber
row = [DateTime.parse("2023-03-06 20:00:00")]
DataFrame.new({ date: :date64 }, [row])
```

#### Stack trace

```
NoMatchingPatternError: 2023-03-06T14:00:00-06:00
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_displayable.rb:485:in `block (3 levels) in html_table'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/vector.rb:375:in `map'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/vector.rb:375:in `map'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_displayable.rb:484:in `block (2 levels) in html_table'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_displayable.rb:483:in `select'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_displayable.rb:483:in `with_object'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_displayable.rb:483:in `block in html_table'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_variable_operation.rb:590:in `instance_eval'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_variable_operation.rb:590:in `assign_update'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_variable_operation.rb:512:in `assign'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_displayable.rb:482:in `html_table'
~/ra-test/vendor/bundle/ruby/3.2.0/gems/red_amber-0.4.0/lib/red_amber/data_frame_displayable.rb:287:in `to_iruby'
~/ra-test/ruby/gems/3.2.0/gems/iruby-0.7.4/lib/iruby/display.rb:67:in `block in display'
~/ra-test/ruby/gems/3.2.0/gems/iruby-0.7.4/lib/iruby/display.rb:59:in `each'
~/ra-test/ruby/gems/3.2.0/gems/iruby-0.7.4/lib/iruby/display.rb:59:in `display'
~/ra-test/ruby/gems/3.2.0/gems/iruby-0.7.4/lib/iruby/kernel.rb:215:in `execute_request'
~/ra-test/ruby/gems/3.2.0/gems/iruby-0.7.4/lib/iruby/kernel.rb:139:in `dispatch'
~/ra-test/ruby/gems/3.2.0/gems/iruby-0.7.4/lib/iruby/kernel.rb:127:in `run'
~/ra-test/ruby/gems/3.2.0/gems/iruby-0.7.4/lib/iruby/command.rb:106:in `run_kernel'
~/ra-test/ruby/gems/3.2.0/gems/iruby-0.7.4/lib/iruby/command.rb:37:in `run'
~/ra-test/ruby/gems/3.2.0/gems/iruby-0.7.4/bin/iruby:5:in `<top (required)>'
~/ra-test/vendor/bundle/ruby/3.2.0/bin/iruby:25:in `load'
~/ra-test/vendor/bundle/ruby/3.2.0/bin/iruby:25:in `<main>' 
```

**Comment by heronshoes** [comment]
Hi @tlrasor, thanks for the report!

This is because the Pattern matching clause in `DataFrame#iruby` for Temporal type has no matching condition neither `else` clause.

Fortunately, I fixed this just yesterday😄 (https://github.com/heronshoes/red_amber/commit/d37db9fc272622bab563fc1d4209463b484e1209)
Please use latest HEAD if you can. I'll release next 0.4.1 gem out as soon as I can.

For your information, you can also change the output mode to use IRuby with plain text.
```ruby
ENV['RED_AMBER_OUTPUT_MODE'] = 'Plain'
```

**Comment by heronshoes** [comment]
Fixed in #193 .
